import {Color} from '~types';
import {fromHex} from '~utils/color';

const palette: Array<[Color, string]> = [
    [fromHex('#ffffff'), 'White'],
    [fromHex('#e9dac0'), 'Ecru'],
    [fromHex('#f7f51f'), 'Sun yellow'],
    [fromHex('#ecdd1e'), 'Bright yellow'],
    [fromHex('#de9a2c'), 'Golden yellow'],
    [fromHex('#c57d29'), 'Burn orange'],
    [fromHex('#ce822c'), 'Pumpkin orange'],
    [fromHex('#cf5c3a'), 'Deep orange'],
    [fromHex('#d88272'), 'Salmon'],
    [fromHex('#b82c8b'), 'Pink'],
    [fromHex('#cb3c38'), 'Scarlet'],
    [fromHex('#a02f3f'), 'Burgundy'],
    [fromHex('#8d2b4f'), 'Vermillion'],
    [fromHex('#8f80bc'), 'Lilac'],
    [fromHex('#4b296d'), 'Purple'],
    [fromHex('#482e90'), 'Violet'],
    [fromHex('#6d6fab'), 'Periwinkle'],
    [fromHex('#9c352e'), 'Russet'],
    [fromHex('#cb3955'), 'Cherry red'],
    [fromHex('#a9363e'), 'Fire red'],
    [fromHex('#9d2d46'), 'Crimson'],
    [fromHex('#ca2f8b'), 'Hot fuchsia'],
    [fromHex('#374fa3'), 'Sky blue'],
    [fromHex('#2e3176'), 'Saphire blue'],
    [fromHex('#373c98'), 'Brilliant blue'],
    [fromHex('#5e98d9'), 'Turquoise'],
    [fromHex('#21095e'), 'Royal blue'],
    [fromHex('#232a5e'), 'Navy blue'],
    [fromHex('#6eb34a'), 'Kelly green'],
    [fromHex('#d5e12d'), 'Chartreuse'],
    [fromHex('#48823d'), 'Emerald'],
    [fromHex('#1e3240'), 'Spruce'],
    [fromHex('#32526a'), 'Teal'],
    [fromHex('#865537'), 'Chestnut'],
    [fromHex('#ac6e24'), 'Aztec gold'],
    [fromHex('#82734c'), 'Olive'],
    [fromHex('#4d331c'), 'Brown'],
    [fromHex('#cd9b27'), 'Gold ochre'],
    [fromHex('#181d54'), 'Gun metal'],
    [fromHex('#a0959f'), 'Silver gray'],
    [fromHex('#1c0314'), 'Jet black'],
];

export default palette;
